const data = {
  products: [
    {
      _id: "1",
      name: "An Ode Hope ver. Dino photocard",
      category: "photocards",
      image: "../images/product-1.png",
      price: 6,
      group: "Seventeen",
      countInStock: 1,
      description: {
        album: "An Ode",
        members: "Dino",
        version: "Hope",
        preorder: "nee",
      },
    },
    {
      _id: "2",
      name: "More&More Tzuyu photocard",
      category: "photocards",
      image: "../images/product-2.png",
      price: 4,
      group: "Twice",
      countInStock: 1,
      description: {
        album: "More&More",
        members: "Tzuyu",
        version: "niet van toepassing",
        preorder: "nee",
      },
    },
    {
      _id: "3",
      name: "Awaken The World Hendery cirlecard",
      category: "photocards",
      image: "../images/product-3.png",
      price: 3,
      group: "WayV",
      countInStock: 0,
      description: {
        album: "Awaken The World",
        members: "Hendery",
        version: "Awaken",
        preorder: "nee",
      },
    },
    {
      _id: "4",
      name: "Fever: part 3 Diary ver. Jongho MMT photocard",
      category: "photocards",
      image: "../images/product-4.png",
      price: 10,
      group: "Ateez",
      countInStock: 1,
      description: {
        album: "Fever: Part 1",
        members: "Jongho",
        version: "Diary",
        preorder: "MyMusicTaste(MMT)",
      },
    },
    {
      _id: "5",
      name: "Hide&Seek Ireh MK photocard",
      category: "photocards",
      image: "../images/product-5.png",
      price: 5,
      group: "Purple Kiss",
      countInStock: 1,
      description: {
        album: "Hide&Seek",
        members: "Ireh",
        version: "niet van toepassing",
        preorder: "Music Korea (MK)",
      },
    },
    {
      _id: "6",
      name: "Round 2: Hole Gyehyeon Makestar photocard",
      category: "photocards",
      image: "../images/product-6.png",
      price: 5,
      group: "Verivery",
      countInStock: 1,
      description: {
        album: "Round 2: Hole",
        members: "Gyehyeon",
        version: "Reality",
        preorder: "Makestar",
      },
    },
    {
      _id: "7",
      name: "Crazy In Love Chaeryoung photocard",
      category: "photocards",
      image: "../images/product-7.png",
      price: 4,
      group: "Itzy",
      countInStock: 1,
      description: {
        album: "Crazy In Love",
        members: "Chaeryoung",
        version: "niet van toepassing",
        preorder: "nee",
      },
    },
    {
      _id: "8",
      name: "Guess Who Lia photocard",
      category: "photocards",
      image: "../images/product-8.png",
      price: 4,
      group: "Itzy",
      countInStock: 1,
      description: {
        album: "Guess Who",
        members: "Lia",
        version: "niet van toepassing",
        preorder: "nee",
      },
    },
  ],
};

export default data;
